### ISSUE TITLE
No always compression

### ISSUE THREAD

**Issue by marcobambini** [sqlitecloud/sqlitecloud-go#2]

**Comment by danielebriggi** [comment]
Compress is set to NO in cli as default value:
https://github.com/sqlitecloud/go-sdk/blob/e87c739b1a71cb748d932386c0c1b06f8eb34497/cli/sqlc.go#L320-L321

as well for for the connnection string:
https://github.com/sqlitecloud/go-sdk/blob/e87c739b1a71cb748d932386c0c1b06f8eb34497/connection.go#L148-L158

Then the value is handled in the right way:
https://github.com/sqlitecloud/go-sdk/blob/e87c739b1a71cb748d932386c0c1b06f8eb34497/connection.go#L503-L512

I'm adding a test to confirm this.

**Comment by danielebriggi** [comment]
as talked with Marco, we can enable `compression` by default on every sdk
