### ISSUE TITLE
sqlitecloud and gorm

### ISSUE THREAD

**Issue by facundofarias** [sqlitecloud/sqlitecloud-go#4]
Hello there,

First of all, thanks for the project, looks amazing!
Now, I am not an experienced Go Developer, but I am not able to make it work between sqlitecloud and gorm. Let's say I have the following snippet:
```
	if db, err = gorm.Open(sqlitecloud.Connect(connectionString), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	}); err != nil {
		return err
	}
```
I'm having the following error: 
**multiple-value sqlitecloud.Connect(connectionString) (value of type (*sqlitecloud.SQCloud, error)) in single-value context**

Any idea?
Thanks

**Comment by andinux** [comment]
Hi @facundofarias 
This library can be used to communicate with SQLite Cloud servers, but it is not a drop-in replacement for the standard sqlite3 libraries like `github.com/mattn/go-sqlite3`, so it cannot be used with the GORM SQLite Driver. We are working on a new library that will be fully compatible with the established sqlite3 API. It will allow you to migrate your SQLite to the cloud while continuing to use your existing Go codebase..

**Comment by facundofarias** [comment]
I see! That would be great.
Thanks

**Comment by farhanfadila1717** [comment]
Hi, any update to support `github.com/mattn/go-sqlite3`?
